### ISSUE TITLE
Set a valid Content-Type instead of */* in the swagger to generate the client with correct behavior.

### ISSUE THREAD

**Issue by krabhishek8260** [kubernetes-client/csharp#10]

**Comment by dmirmilshteyn** [comment]
Is there a workaround for this (other than manually making the changes in the code)? Kubernetes 1.2+ now requires a correct Content-Type header to be set, otherwise the request is rejected - rendering large parts of this library non-functional. Using custom headers fails, because the Content-Type header is overwritten when it is being set to */*.

**Comment by krabhishek8260** [comment]
We need to change the swagger pre processing scripts to set the right Content-Type in the swagger.

**Comment by brendandburns** [comment]
I'll look into fixing this in post-processing...
