### ISSUE TITLE
Windows Server 2022 Standard TLS handshake failed with Azure AKS

### ISSUE THREAD

**Issue by tg123** [kubernetes-client/csharp#1033]
Windows Server 2022 Standard

_Originally posted by @mig0000 in https://github.com/kubernetes-client/csharp/discussions/1031#discussioncomment-3715572_

**Comment by tg123** [comment]
cant repro using windows 2022 on azure and aks

**Comment by mig0000** [comment]
The problem was the computer that was connecting to AKS. **The IT team (systems crew) had restricted some permissions** (I don't know which ones) through system policies, and it gave errors with the client certificates. Although the user was an administrator, the system must have restricted certain functionalities with respect to certificates.
