### ISSUE TITLE
Fractions library isn't strongly named..

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/csharp#160]
Running examples I see:

```
CSC : warning CS8002: Referenced assembly 'Fractions, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [/home/brendan/src/kubernetes-client/csharp/src/KubernetesClient/KubernetesClient.csproj]
```

@qmfrederik is there a way to fix this?

**Comment by qmfrederik** [comment]
Is this on the .NET Framework or on .NET Core?

**Comment by lamchester** [comment]
.NET Framework

**Comment by lamchester** [comment]
(poke) any update on this?

**Comment by tg123** [comment]
https://github.com/danm-de/Fractions

**Comment by lamchester** [comment]
Yes, that's the fractions library. The problem is, it's not signed. With .NET Framework, assemblies that are strong name signed can't load assemblies that aren't.

Can you all either:
 - Don't strong name sign the KubernetesClient assembly in the published nuget package. Then we can get the .NET Framework to not enforce strong names
 - Depend on a version of the Fractions library that's strong name signed. I don't know if one exists.
 - Don't use the Fractions library

Obviously the latter two options would be preferable, in case KubernetesClient needs to be referenced from a strong name signed assembly.

**Comment by brendandburns** [comment]
@lamchester I think the right thing to do here is to import the relevant Fractions.cs files into this repository and point the code at the local copy instead. The licenses are compatible, I'd be happy to review the PR.

Thanks

**Comment by RohanNagar** [comment]
This can be closed now!

**Comment by brendandburns** [comment]
closing! :)

**Comment by ArchangelSDY** [comment]
Hi, do you have any timeline to publish a new NuGet package with this fix? Currently we are using v1.2.0 and are blocked by this issue.

**Comment by brobichaud** [comment]
> Hi, do you have any timeline to publish a new NuGet package with this fix? Currently we are using v1.2.0 and are blocked by this issue.

Yeah I too am dead-ended on trying to use this k8s client.

**Comment by qmfrederik** [comment]
Have you tried any of the more recent versions, like 1.4.1-g1600e44b00?
PS - Not sure why the git version is appended to builds coming from master, that's probably something we'll need to fix

**Comment by brobichaud** [comment]
> Have you tried any of the more recent versions, like 1.4.1-g1600e44b00?
> PS - Not sure why the git version is appended to builds coming from master, that's probably something we'll need to fix

No I've only tried the official releases. Can you guys push a new build up to nuget?
