### ISSUE TITLE
Export Control Classification Number (ECCN)

### ISSUE THREAD

**Issue by fabiocbr75** [kubernetes-client/csharp#1600]
**Describe the bug**
Is it true that the Kubernetes-Client, specifically the C# version, is classified as ECCN: 5D002 according to the Linux Foundation export document (https://www.linuxfoundation.org/legal/export)? 
This classification poses a problem due to its very restricted nature and it is ok for Kubernetes but it's too much for the client libraries that are a wrap over HTTP.

**Expected behavior**
The client libraries should be of lesser classification (not the ECCN: 5D002)
![ECCN_Kubernetes-Client](https://github.com/user-attachments/assets/cd3c9e76-43df-4789-a910-13c23feb50b3)

**Comment by tg123** [comment]
seems it is not specific to .net sdk only.

**Comment by fabiocbr75** [comment]
Yes, it's not only specific to .net sdk but all kubernetes-client repo and it's a problem.

**Comment by brendandburns** [comment]
You would have to ask the Linux Foundation/CNCF lawyers about this. This appears to be set up to include all repositories that are associated with the Kubernetes project, so agree with @tg123 that this isn't specific to the dotnet client. If this can be fixed, it will need to be fixed by the Linux Foundation/CNCF.

I'm going to close this issue here, since there's nothing we can do.
