### ISSUE TITLE
AuthTests.Cert() test fails

### ISSUE THREAD

**Issue by itowlson** [kubernetes-client/csharp#214]
The `AuthTests.Cert()` test is failing in CI, and also fails when I run `dotnet test` locally on Windows.  Is there some pre-configuration that needs to be done for this to pass?

**Comment by itowlson** [comment]
That test only runs on 2.1; we could instead ignore the test, and then at least we'd know that we hadn't broken other things on 2.1?

**Comment by tg123** [comment]
Only on windows, so the CI is not broken.
We'd better add CI window.

Maybe we should ignore it first, but I would like to figure out the root cause.

**Comment by brendandburns** [comment]
I turned this off on OS X (it passes on Linux) in #218 

We should investigate further, but CI is now restored...

**Comment by Marcele1987** [comment]
Seems to work when I add `X509VerificationFlags.IgnoreNotTimeValid` to `chain.ChainPolicy.VerificationFlags = X509VerificationFlags.AllowUnknownCertificateAuthority` in `CertificateValidationCallBack` in Kubernetes.ConfigInit.cs. 

`var isValid = chain.Build((X509Certificate2)certificate);` returns true then.

Probably because the NotAfter date of the CaCert is 12/10/2018.

![certdate](https://user-images.githubusercontent.com/33805250/49409485-c6d79500-f758-11e8-8f94-d901dbf290b2.PNG)

**Comment by tg123** [comment]
@Marcele1987 another problem, I will update cert

**Comment by brendandburns** [comment]
@tg123 @itowlson 

Is this still a problem? I just ran dotnet test on my windows machine and it appears to work correctly...

**Comment by tg123** [comment]
@brendanburns fixed. I updated the cert in #223.
