### ISSUE TITLE
Corelate Nuget releases with GitHub commits/releases

### ISSUE THREAD

**Issue by gaziqbal** [kubernetes-client/csharp#278]
Apologies if this is not the correct forum. I'm having difficulty understanding how the Nuget releases map to the GitHub commits and releases. I only see 3 releases on GitHub. However it seems that there is a fairly regular release cadence on Nuget.

How which Nuget version maps to which commit? For example, I'd like a package which includes https://github.com/kubernetes-client/csharp/commit/fd1736f3e79c2c815c10ddafd4514257145b6f4e.

**Comment by qmfrederik** [comment]
Good question. 

Releases are pushed to NuGet during Travis builds from master.

As a rule of thumb, since packages are only pushed for master builds, is to correlate the publish time in NuGet with the commit time.

The '100% sure' way to find out the NuGet package which was produced by a build:

1. Go to the commit history in GitHub - https://github.com/kubernetes-client/csharp/commits/master
2. Find a commit with green CI check mark (after the text `X days ago`)
3. Click that CI check mark. It will show a list of CI checks which have completed.
4. Click the Travis CI link.
5. Open the Linux job.
5. Search the build log for `GitBuildVersionSimple`. This will get your build version.

For example, for fd1736f, the Travis build was [510171785](https://travis-ci.org/kubernetes-client/csharp/builds/510171785?utm_source=github_status&utm_medium=notification). 

The [logs](https://travis-ci.org/kubernetes-client/csharp/jobs/510171786#L3589) show that the NuGet package version is 1.5.12.

**Comment by gaziqbal** [comment]
Thanks for the help. It'd be great to create a release in GitHub which corresponds to the NuGet release :)
