### ISSUE TITLE
Cant get avalaibleReplicas

### ISSUE THREAD

**Issue by eflorespalma** [kubernetes-client/csharp#280]
Hi everybody,

I have one problem accessing to some information about my deployments.

```
IKubernetes client = new Kubernetes(config);
            var deploymentListResp = client.ListNamespacedPodWithHttpMessagesAsync("default", watch: true).Result;
            using (deploymentListResp.Watch<Appsv1beta1Deployment>((type, item) =>
            {
                Console.WriteLine(type);
                Console.WriteLine(item.Spec.Replicas);
                Console.WriteLine(item.Status.AvailableReplicas);
                Console.WriteLine(item.Metadata.Name);

                Console.WriteLine("==on watch event==");
            }))
            {
                Console.WriteLine("press ctrl + c to stop watching");

                var ctrlc = new ManualResetEventSlim(false);
                Console.CancelKeyPress += (sender, eventArgs) => ctrlc.Set();
                ctrlc.Wait();
            }
```

Replicas and AvailableReplicas always is null, Is there any solution for that? Thx

**Comment by brendandburns** [comment]
you're watching here. If you want to watch you need to use the Watch helper class:

https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/IKubernetes.Watch.cs
https://github.com/kubernetes-client/csharp/blob/master/examples/watch/Program.cs

Otherwise setting watch to false, I think will fix things, please re-open if setting watch to false doesn't fix things.
