### ISSUE TITLE
Why do the Patch*CustomObject* methods use Merge Patch headers?

### ISSUE THREAD

**Issue by JoelOtter** [kubernetes-client/csharp#305]
Hi folks,

We've been trying to use the `PatchNamespacedCustomObject` method to modify some fields in a CRD instance. This throws an error, as we're sending a `V1Patch` but these methods set the header to `merge-patch+json`, thus k8s can't unmarshal it at the other end. All the other Patch methods we can see use `json-patch+json`.

What is the rationale behind having these methods send a different header? The `V1Patch` class doesn't seem to support merge patches at this time, and while we can certainly work out how to form the JSON ourselves it seems like we're missing something here.

Cheers!

**Comment by brendandburns** [comment]
There's a patch example here:

**Comment by JoelOtter** [comment]
Thanks @brendandburns - that example uses `PatchNamespacedPod`. My question is about the `PatchNamespacedCustomObject` method, which sets a different header to the former.

**Comment by vinisoto** [comment]
@brendandburns,

The problem here is that `PatchNamespacedCustomObject` always fails with: 

> "couldn't get version/kind; json parse error: json: cannot unmarshal array into Go value of type struct { APIVersion string \"json:\\\"apiVersion,omitempty\\\"\"; Kind string \"json:\\\"kind,omitempty\\\"\" }"

The reason is that, as @JoelOtter explained, `PatchNamespacedPod` always sets the PATCH type as "merge" by adding this header to the PATCH HTTP request:

`_httpRequest.Content.Headers.ContentType=System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/merge-patch+json");`

Which is the equivalent of:

`kubectl patch webapp simplewebapp --namespace vanilla-asp --type merge --patch '[{\"op\":\"replace\", \"path\": \"/some/json/path\", \"value\":\"somevalue\"}]'` which also fails with the same "cannot unmarshall ..." error.

If we change the merge type to 'json', it succeeds:

`kubectl patch webapp simplewebapp --namespace vanilla-asp --type json --patch '[{\"op\":\"replace\", \"path\": \"/some/json/path\", \"value\":\"somevalue\"}]'`

**Is there a reason why `PatchNamespacedPod` is the only PATCH operation that sets the PATCH type to "merge"?** or should it be changed to 'json' just like all the other PATCH operations (for example, PatchNamespacedPod, PatchNamespacedSecret, etc.) as below?:

`_httpRequest.Content.Headers.ContentType =System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json-patch+json; charset=utf-8");`

@aarthisk

**Comment by IvanJosipovic** [comment]
I'm facing the same issue. Do you have a working example of PatchNamespacedCustomObject?

**Comment by tg123** [comment]
should be fixed in latest version
reopen if still have this issue

**Comment by milanchavda** [comment]
I'm still facing same issue with latest version
