### ISSUE TITLE
How do I scale existing deployment replicas?

### ISSUE THREAD

**Issue by DotNetRockStar** [kubernetes-client/csharp#455]
Hi there.  I am trying to scale the replicas of a deployment.  I want to execute this using the c# driver

```
kubectl scale --replicas=10 deployments/myCoolDeployment -n mySuperCoolNamespace
```

How would I go about doing this using the kubernetes client?

Thanks in advance!
 Jerrod

**Comment by brendandburns** [comment]
You can use Patch similar to the example here:

https://github.com/kubernetes-client/csharp/blob/master/examples/patch/Program.cs

But instead of modifying a V1Pod you want to modify the V1Deployment. https://github.com/kubernetes-client/csharp/blob/8ab95b6b920e8a10b4c0122e09d158be2005aa15/src/KubernetesClient/generated/Models/V1Deployment.cs)

**Comment by brendandburns** [comment]
The other alternative is to read the V1Deployment, change the object and then update with `ReplaceNamespacedDeployment(...)`

**Comment by iamjxb** [comment]
Does the ReplaceNamespacedDeployment delete then create? or it's like the apply? Thanks.

**Comment by brendandburns** [comment]
@iamjxb Replace is the same as `kubectl replace` it's different than `kubectl apply` which does some client side work to track versions, but it does replace in-place, it doesn't delete.

**Comment by brendandburns** [comment]
I'm going to close this, because I think the question is answered.
