### ISSUE TITLE
ConnectGetNamespacedServiceProxy does not work

### ISSUE THREAD

**Issue by pragyamehta** [kubernetes-client/csharp#461]
I am trying the below call :

client.ConnectGetNamespacedServiceProxy("myserviceName", "myNamespace", "api/ping");
to hit the /api/ping endpoint of the service "myserviceName" in the namespace "myNamespace"

I get a NotFound exception. Is this the correct way to use this API? My assumption is that the Client should open a proxy to the cluster and make an Http call to the given service endpoint and return the response back to me but that is not happening.

**Comment by brendandburns** [comment]
In order to open a port-forwarding connection you should use the PortForward custom API as shown in this example:
https://github.com/kubernetes-client/csharp/blob/master/examples/portforward/PortForward.cs

The generated `Connect...` calls don't work because OpenAPI doesn't understand the WebSockets protocol that PortForward uses.
