### ISSUE TITLE
Patch Env appends new Env and not append to the same existing one. 

### ISSUE THREAD

**Issue by stubclan** [kubernetes-client/csharp#465]
Applying Patch with new ENV keeps adding new ENV on the container and not append to existing one. If you print that ENV var in the container then you'd see that only the latest has applied.

```csharp
var patch = new JsonPatchDocument<V1Deployment>();

var testENV = new V1EnvVar() {
    Name = "TESTENV",
    Value = "TestingENV"
 };
               
patch.Add(e => e.Spec.Template.Spec.Containers[0].Env, testENV);
//Client below is a Kubernetes Client
var patchedDeployment = await _client.PatchDeployment(patch, "pleasefindthisone", deploymentNamespace);
```

After the above code is run three times, if you look at the deployment ENV vars you'd see something like below:
![image](https://user-images.githubusercontent.com/6322130/88097353-a3e03b80-cb5d-11ea-9dc9-5c4147866201.png)

Is there a way to modify this so instead, we can append to already existing variable?

**Comment by brendandburns** [comment]
You need to use `patch.Replace(...)` instead of `patch.Add(...)`

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.jsonpatch.jsonpatchdocument.replace?view=aspnetcore-3.0#Microsoft_AspNetCore_JsonPatch_JsonPatchDocument_Replace_System_String_System_Object_

http://jsonpatch.com/#replace
