### ISSUE TITLE
Minimum permission for Pod Creation

### ISSUE THREAD

**Issue by som-nitjsr** [kubernetes-client/csharp#481]
I am running a pod  in aks. and from this pod i want create some other pods/ different image based on some logic . this works only when i give **cluster-admin**.
ideally my code should work with less permission  like pod/ get,watch,list,update,create,update,pathch.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: #{devOps.stage.ns}#-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  **name: cluster-admin**
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:#{devOps.stage.ns}#:xyz

**Comment by brendandburns** [comment]
See the documentation here:

https://kubernetes.io/docs/reference/access-authn-authz/rbac/

I'm closing this issue because it is a general Kubernetes question not related to this client.

Please check out the Kubernetes slack (https://slack.kubernetes.io) if you have further questions, it's a great resource for general Kubernetes assistance.
