### ISSUE TITLE
Naming of some methods is inconsistent.

### ISSUE THREAD

**Issue by simonvane** [kubernetes-client/csharp#490]
You gave this useful guidance on your naming patterns:
https://github.com/kubernetes-client/csharp/issues/487#issuecomment-702862014

That was very helpful but I came across some inconsistencies. There may be a good reason for them but they weren't obvious to me.

The ones I spotted were for custom objects i.e. `GetNamespacedCustomObject...` rather than `ReadNamespacedCustomObject...`.

Thanks.

**Comment by brendandburns** [comment]
I think the root cause of this is in the swagger documents and how they are written.

The custom object swagger is here:
https://github.com/kubernetes-client/gen/blob/master/openapi/custom_objects_spec.json

And the Kubernetes swagger is here:
https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec

I'm not sure what the difference is, but I suspect that's the cause.
