### ISSUE TITLE
Framework no longer supported

### ISSUE THREAD

**Issue by KnicKnic** [kubernetes-client/csharp#743]
In PR https://github.com/kubernetes-client/csharp/pull/603 the code was switched from emitting .netstandard 2.0 to .netstandard 2.1 . Can we change this back to .netstandard 2.0 Otherwise cannot use this package with .net Framework. 
@tg123

**Comment by tg123** [comment]
lol going to drop netstandard2.1 as well for crypot and json api support
May I know why do you'd like netstandard2?
it is very easy to upgrade to net5/6

**Comment by brendandburns** [comment]
Since dotnet 2.1 is EOL'd in favor of 3.1 or 5/6 I don't think we really can or should support them, users should upgrade.

I'm not sure that the work needed to support a deprecated platform is worth it for this project given the limited resources that we currently have.

**Comment by KnicKnic** [comment]
@brendandburns  please see table https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support notice .netstandard vs .net vs .net core vs .netframework.
* .netstandard is the compatibility layer
* .net (can be though of as .netcore's new name, this is a gross simplification)


.Net CORE 2.1 is EOL this is not .net standard

**Comment by tg123** [comment]
netcoreapp3.0 which impl the one netstandard2.1 is also eol
https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/ 
net5+ is new netstandard

However, I agree to provide support to netframework4.8 since it is still in support. (could be via netstandard2.0)
One solution to this might be splitting the nuget to multiple parts, making websocket related to a separated nuget.
this is also being discussed here https://github.com/kubernetes-client/csharp/pull/665#issuecomment-883983454

**Comment by brendandburns** [comment]
@KnicKnic thanks for the explanation (all of the .NET versioning stuff is pretty opaque to me)

I can see the value in supporting .NET framework 4.8 to handle legacy apps. However, I'm not certain that we have the resources to do it. We would be open to proposals as to how to best accomplish this support and also to support the work to actually implement the proposal once we design it.

Perhaps the best approach would be to send a PR with a Markdown design document and we can comment/iterate on that until we are happy with the approach?
