### ISSUE TITLE
Samples should dispose the clients?

### ISSUE THREAD

**Issue by taspeotis** [kubernetes-client/csharp#840]
The readme and example folders are full of things like:

```
var client = new Kubernetes(config);
```

Surely this should be `using var client = ...` since `Kubernetes` implements `IDisposable`?

**Comment by tg123** [comment]
Nice to have, but not a must.
it is a good practice to call `Dispose` if the obj impled it.
The reason Kuberenetes object is Disposable is because the inner property httpclient is Disposable. The dispose will call httpclient's dispose to clean up all httpclient's resources.


To set a better example, you are welcome to send a PR to add `using` to them

**Comment by zhiweiv** [comment]
I think it is recommended to not dispose httpclient frequently, use it as singleton, so it is good to use singleton k8s client also.
